// Auto-generated by: npm run supabase:types
// Run `npm run supabase:types` after schema changes (requires: supabase login)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: '12';
  };
  public: {
    Tables: {
      clients: {
        Row: {
          id: string;
          user_id: string;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          birthday: string | null;
          skin_type: string | null;
          avatar_url: string | null;
          has_routine_access: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          birthday?: string | null;
          skin_type?: string | null;
          avatar_url?: string | null;
          has_routine_access?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          birthday?: string | null;
          skin_type?: string | null;
          avatar_url?: string | null;
          has_routine_access?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sleep_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          hours: number;
          quality: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          hours: number;
          quality: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          hours?: number;
          quality?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      sport_entries: {
        Row: {
          id: string;
          user_id: string;
          sport_type_id: string;
          date: string;
          duration: number;
          intensity: number;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          sport_type_id: string;
          date: string;
          duration: number;
          intensity: number;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          sport_type_id?: string;
          date?: string;
          duration?: number;
          intensity?: number;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'sport_entries_sport_type_id_fkey';
            columns: ['sport_type_id'];
            isOneToOne: false;
            referencedRelation: 'sport_types';
            referencedColumns: ['id'];
          },
        ];
      };
      meal_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          food_name: string | null;
          photo_url: string | null;
          note: string | null;
          meal_type: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          food_name?: string | null;
          photo_url?: string | null;
          note?: string | null;
          meal_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          food_name?: string | null;
          photo_url?: string | null;
          note?: string | null;
          meal_type?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      stress_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          level: number;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          level: number;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          level?: number;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      observation_entries: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          positives: string[];
          negatives: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          positives?: string[];
          negatives?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          positives?: string[];
          negatives?: string[];
          created_at?: string;
        };
        Relationships: [];
      };
      sport_types: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      diagnoses: {
        Row: {
          id: string;
          user_id: string;
          result_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          result_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          result_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      push_tokens: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          platform: string;
          device_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          platform: string;
          device_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          platform?: string;
          device_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      app_config: {
        Row: {
          id: string;
          key: string;
          value: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
